#!/usr/bin/env node
/**
 * quality-gate.mjs — ClinicOS Engineering Quality Platform orchestrator
 * (Phase 9 · Part 2 + Part 13).
 *
 * The single command that runs EVERY automated quality gate, prints a summary,
 * generates `docs/reports/engineering-quality-report.md`, and exits non-zero if
 * any blocking gate failed. This is what CI runs and what `pnpm quality` runs.
 *
 * Gates (blocking unless noted):
 *   typecheck · lint · format · test · build · architecture · duplicates ·
 *   tokens · i18n · ds:registry · assets · perf-budget
 *
 * Flags:
 *   --quick     skip the heavy gates (build, test) — for fast local pre-commit.
 *   --no-report don't (re)write the markdown report.
 *
 * Usage: `pnpm quality`  ·  `pnpm quality:quick`
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const args = new Set(process.argv.slice(2));
const QUICK = args.has('--quick');
const WRITE_REPORT = !args.has('--no-report');
const OUT = 'docs/reports/engineering-quality-report.md';

// Resolve runners robustly. When launched via a package manager, env exposes
// the node binary + the PM cli even when `pnpm` is not on PATH (e.g. via
// Corepack). Fall back to bare `pnpm`/`node`.
const NODE = process.execPath;
const PM_CLI = process.env.npm_execpath;
const q = (p) => `"${p}"`;
/** `pnpm run <script>` as a PATH-independent invocation. */
const pm = (script) => (PM_CLI ? `${q(NODE)} ${q(PM_CLI)} run ${script}` : `pnpm run ${script}`);
/** `node <file>` using the current node binary. */
const node = (file) => `${q(NODE)} ${file}`;

/** A gate = one command. `heavy` gates are skipped under --quick. */
const GATES = [
  { id: 'typecheck', label: 'TypeScript (strict)', cmd: pm('typecheck'), part: 'Types' },
  { id: 'lint', label: 'ESLint (rules + boundaries + cycles)', cmd: pm('lint'), part: 'Lint' },
  { id: 'format', label: 'Prettier', cmd: pm('format:check'), part: 'Format' },
  {
    id: 'architecture',
    label: 'Architecture validation',
    cmd: node('scripts/quality/validate-architecture.mjs'),
    part: 'Part 4',
  },
  {
    id: 'duplicates',
    label: 'Duplication gate',
    cmd: node('scripts/quality/check-duplicates.mjs'),
    part: 'Part 2',
  },
  {
    id: 'tokens',
    label: 'Design-token compliance',
    cmd: node('scripts/quality/check-tokens.mjs'),
    part: 'Part 3',
  },
  {
    id: 'i18n',
    label: 'Localization validation',
    cmd: node('scripts/quality/check-i18n.mjs'),
    part: 'Part 7',
  },
  {
    id: 'ds-registry',
    label: 'Component registry',
    cmd: node('scripts/ds-registry.mjs'),
    part: 'Registry',
  },
  { id: 'assets', label: 'Asset hygiene', cmd: node('scripts/check-assets.mjs'), part: 'Assets' },
  {
    id: 'test',
    label: 'Unit + a11y tests (Vitest)',
    cmd: pm('test'),
    part: 'Test',
    heavy: true,
  },
  { id: 'build', label: 'Production build', cmd: pm('build'), part: 'Build', heavy: true },
  {
    id: 'perf',
    label: 'Performance budget',
    cmd: node('scripts/quality/check-perf-budget.mjs'),
    part: 'Part 5',
  },
];

const results = [];
console.log(
  `\nClinicOS — Engineering Quality Platform${QUICK ? ' (quick)' : ''}\n${'='.repeat(48)}`,
);

for (const gate of GATES) {
  if (QUICK && gate.heavy) {
    results.push({ ...gate, status: 'skipped', ms: 0 });
    console.log(`↷ ${gate.label} — skipped (--quick)`);
    continue;
  }
  const start = Date.now();
  let status = 'pass';
  let tail = '';
  try {
    execSync(gate.cmd, { stdio: 'pipe', encoding: 'utf8' });
  } catch (e) {
    status = 'fail';
    tail = `${e.stdout ?? ''}${e.stderr ?? ''}`.trim().split('\n').slice(-6).join('\n');
  }
  const ms = Date.now() - start;
  results.push({ ...gate, status, ms, tail });
  console.log(`${status === 'pass' ? '✓' : '✗'} ${gate.label} (${(ms / 1000).toFixed(1)}s)`);
  if (tail) console.log(tail.replace(/^/gm, '    '));
}

const failed = results.filter((r) => r.status === 'fail');
const passed = results.filter((r) => r.status === 'pass');
const skipped = results.filter((r) => r.status === 'skipped');

if (WRITE_REPORT) {
  const now = new Date().toISOString();
  const icon = (s) => ({ pass: '✅ pass', fail: '❌ FAIL', skipped: '↷ skipped' })[s];
  let md = `<!-- GENERATED by \`pnpm quality\` (scripts/quality/quality-gate.mjs) — DO NOT EDIT BY HAND. -->\n\n`;
  md += `# ClinicOS — Engineering Quality Report\n\n`;
  md += `> Generated: ${now} · Gates: ${GATES.length} · `;
  md += `Passed: ${passed.length} · Failed: ${failed.length} · Skipped: ${skipped.length}\n\n`;
  md += `**Overall: ${failed.length === 0 ? '✅ GREEN — all blocking gates passed.' : `❌ RED — ${failed.length} gate(s) failed.`}**\n\n`;
  md += `| Gate | Scope | Result | Time |\n| --- | --- | --- | --- |\n`;
  for (const r of results) {
    md += `| ${r.label} | ${r.part} | ${icon(r.status)} | ${(r.ms / 1000).toFixed(1)}s |\n`;
  }
  md += `\n`;
  if (failed.length) {
    md += `## Failures\n\n`;
    for (const r of failed) {
      md += `### ❌ ${r.label}\n\n\`${r.cmd}\`\n\n\`\`\`\n${r.tail || '(no output captured)'}\n\`\`\`\n\n`;
    }
  }
  md += `_Run \`pnpm quality\` to regenerate. Gate definitions: [docs/engineering/QualityGates.md](../engineering/QualityGates.md)._\n`;
  writeFileSync(OUT, md);
  console.log(`\n✓ Wrote ${OUT}`);
}

console.log(`\n${'='.repeat(48)}`);
console.log(
  `Result: ${failed.length === 0 ? 'GREEN ✓' : `RED ✗ (${failed.map((r) => r.id).join(', ')})`}`,
);
process.exit(failed.length === 0 ? 0 : 1);
