/**
 * Public API for the design-system Component Registry.
 *
 * Import registry metadata from here (`import { COMPONENT_REGISTRY } from
 * '@shared/design-system'`). The registry is validated + the human catalog is
 * generated by `pnpm ds:registry`.
 */
export * from './component-registry';
